# Generated by Django 5.2.11 on 2026-02-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Um usuário com este e-mail já existe.'}, max_length=254, unique=True),
        ),
    ]
