# Generated by Django 5.2.11 on 2026-02-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cor_hex', models.CharField(default='#FF0000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitulo', models.TextField(help_text="O 'Lead' que aparece na home")),
                ('conteudo', models.TextField()),
                ('capa', models.ImageField(upload_to='noticias/capas/')),
                ('meta_description', models.CharField(help_text='Descrição para o Google (SEO)', max_length=160)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('destaque', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='equipe.perfilcolaborador')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postagens', to='noticias.categoria')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
