# Generated by Django 5.2.11 on 2026-02-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_fotogaleria'),
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postagens_usadas', to='equipe.fotogaleria'),
        ),
    ]
