# Generated by Django 5.2.11 on 2026-02-13 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_fotogaleria'),
        ('noticias', '0002_alter_postagem_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postagens_usadas', to='equipe.fotogaleria'),
        ),
    ]
