# Generated by Django 5.2.11 on 2026-02-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Imagem')),
                ('imagem', models.ImageField(upload_to='galeria/%Y/%m/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('fotografo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='equipe.perfilcolaborador')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Galeria de Fotos',
            },
        ),
    ]
