# Generated by Django 5.2.11 on 2026-02-11 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='Nickname')),
                ('cor_perfil', models.CharField(default='#000000', max_length=7, verbose_name='Cor Favorita')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, max_length=300, verbose_name='Sobre mim')),
                ('receber_noticias', models.BooleanField(default=True, verbose_name='Deseja receber novidades?')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Membro',
                'verbose_name_plural': 'Perfis da Comunidade',
            },
        ),
    ]
