# Generated by Django 5.2.11 on 2026-02-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmembro',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='perfilmembro',
            name='discord_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Discord ID'),
        ),
        migrations.AddField(
            model_name='perfilmembro',
            name='instagram_user',
            field=models.CharField(blank=True, max_length=30, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='perfilmembro',
            name='jogos_favoritos',
            field=models.CharField(blank=True, help_text='Ex: LoL, CS2, Valorant', max_length=255, verbose_name='Jogos de Interesse'),
        ),
        migrations.AddField(
            model_name='perfilmembro',
            name='pontos_engajamento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilmembro',
            name='time_coracao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Time Favorito'),
        ),
        migrations.AddField(
            model_name='perfilmembro',
            name='twitter_user',
            field=models.CharField(blank=True, max_length=30, verbose_name='Twitter/X'),
        ),
        migrations.AlterField(
            model_name='perfilmembro',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='perfilmembro',
            name='cor_perfil',
            field=models.CharField(default='#ff0000', max_length=7, verbose_name='Cor de Destaque'),
        ),
        migrations.AlterField(
            model_name='perfilmembro',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nickname/ID'),
        ),
        migrations.AlterField(
            model_name='perfilmembro',
            name='receber_noticias',
            field=models.BooleanField(default=True, verbose_name='Newsletter'),
        ),
    ]
